import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const UPDATED = "28 Ağustos 2026";
const SUPPORT = "fiziktedaviverehabilitasyon00@gmail.com";
const DELETE_URL = "https://dkawrwinmyjvkzioruki.supabase.co/functions/v1/account-deletion";

function page(title: string, body: string) {
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>${title} • FTR Akademi</title><style>:root{color-scheme:light}body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;max-width:860px;margin:0 auto;padding:34px 20px 54px;line-height:1.72;color:#172c35;background:#fff}h1,h2{line-height:1.25;color:#132a34}h1{font-size:2.05rem;margin-bottom:8px}h2{margin-top:2.05rem;font-size:1.23rem}p,li{font-size:1rem}a{color:#166878;font-weight:700}.card{background:#f4f8f9;border:1px solid #d7e4e7;border-radius:16px;padding:18px;margin:20px 0}.meta{color:#61777d}.toc{columns:2;column-gap:30px}.toc a{display:block;margin:5px 0;font-weight:600}@media(max-width:620px){.toc{columns:1}}hr{border:0;border-top:1px solid #dfe7e9;margin:36px 0 18px}</style></head><body><h1>${title}</h1><div class="meta">Son güncelleme: ${UPDATED}</div>${body}<hr><div class="meta">FTR Akademi – Fizik Tedavi ve Rehabilitasyon eğitim uygulaması • Gizlilik iletişimi: <a href="mailto:${SUPPORT}">${SUPPORT}</a></div></body></html>`;
}

const privacy = page("Gizlilik Politikası", `
<div class="card"><strong>Özet:</strong> Bu politika <strong>FTR Akademi – Fizik Tedavi ve Rehabilitasyon</strong> Android uygulamasının kişisel ve hassas kullanıcı verilerini nasıl işlediğini açıklar. FTR Akademi kullanıcı verilerini satmaz, veri brokerlarına aktarmak üzere toplamaz ve davranışsal reklam profili oluşturmaz. Uygulama eğitim amaçlıdır; hasta kayıt sistemi veya tıbbi cihaz değildir.</div>
<div class="toc"><a href="#kapsam">1. Kapsam ve iletişim</a><a href="#veriler">2. İşlenen veri kategorileri</a><a href="#toplanmayan">3. Toplanmayan veriler/izinler</a><a href="#amac">4. İşleme amaçları</a><a href="#dayanak">5. Hukuki dayanaklar</a><a href="#saglayicilar">6. Hizmet sağlayıcılar</a><a href="#aktarim">7. Uluslararası aktarım</a><a href="#saglik">8. Sağlık ve hassas veri</a><a href="#guvenlik">9. Güvenlik</a><a href="#yerel">10. Yerel cihaz verileri</a><a href="#saklama">11. Saklama süreleri</a><a href="#silme">12. Hesap/veri silme</a><a href="#haklar">13. Kullanıcı hakları</a><a href="#cocuklar">14. Çocukların gizliliği</a><a href="#reklam">15. Reklam ve analiz</a><a href="#degisiklik">16. Değişiklikler</a></div>
<h2 id="kapsam">1. Kapsam, uygulama kimliği ve gizlilik iletişimi</h2><p>Bu Gizlilik Politikası, Google Play'de yayımlanacak <strong>FTR Akademi – Fizik Tedavi ve Rehabilitasyon</strong> uygulaması ve uygulamayla bağlantılı hesap, Premium, destek, senkronizasyon ve sunucu hizmetleri için geçerlidir. Gizlilik, KVKK, veri erişimi veya silme talepleri için <a href="mailto:${SUPPORT}">${SUPPORT}</a> adresinden iletişim kurulabilir.</p>
<h2 id="veriler">2. İşlenen veri kategorileri</h2><p>Özellik kullanımına göre aşağıdaki veriler işlenebilir:</p><ul><li><strong>Hesap ve kimlik doğrulama:</strong> e-posta adresi, kullanıcı hesabı kimliği, oturum ve doğrulama kayıtları. Parolalar uygulama veritabanında düz metin olarak saklanmaz; kimlik doğrulama altyapısı tarafından güvenli biçimde yönetilir.</li><li><strong>Kullanıcı tarafından oluşturulan çalışma verileri:</strong> favoriler, kişisel notlar, tamamlanan içerikler, öğrenme ilerlemesi, okuma konumu, quiz denemeleri ve çalışma tercihleri.</li><li><strong>Satın alma ve abonelik verileri:</strong> Google Play ürün kimliği, abonelik durumu, satın alma belirteci/token, sunucu doğrulama sonucu ve hesap eşleştirmesine yönelik teknik tanımlayıcılar. Tam kart veya banka hesabı bilgileri FTR Akademi tarafından alınmaz.</li><li><strong>Destek verileri:</strong> kullanıcı e-posta yoluyla destek talebi gönderirse ad, e-posta, konu ve mesaj içeriği.</li><li><strong>Teknik ve güvenlik kayıtları:</strong> hizmet sağlayıcıların güvenlik, hata ayıklama, dolandırıcılığı önleme ve hizmet sürekliliği amacıyla üretebildiği sınırlı bağlantı/olay günlükleri.</li></ul>
<h2 id="toplanmayan">3. Mevcut sürümde temel özellik olarak toplanmayan veriler ve izinler</h2><p>FTR Akademi mevcut haliyle kesin konum, kişi listesi, SMS/arama kayıtları, mikrofon, kamera, fotoğraf kütüphanesi, Health Connect veya vücut sensörü verilerini temel bir özellik olarak istemez. Reklam kimliğine dayalı davranışsal reklam sistemi kullanılmaz. İleride yeni bir özellik bu veri kategorilerinden birine ihtiyaç duyarsa veri erişimi başlamadan önce gerekli izin/açıklamalar, bu politika ve Google Play Veri Güvenliği beyanları güncellenecektir.</p>
<h2 id="amac">4. Verileri hangi amaçlarla kullanıyoruz?</h2><p>Veriler; hesap oluşturma ve oturum açma, kullanıcı hesabının güvenliğini koruma, tercihleri ve çalışma alanını sunma, cihazlar arası senkronizasyon, Premium yetkilendirme, Google Play satın alımlarını doğrulama, dolandırıcılık ve kötüye kullanımı önleme, kullanıcı desteği sağlama, teknik sorunları inceleme, yasal yükümlülüklere uyma ve hizmetin güvenilirliğini sürdürme amaçlarıyla işlenebilir.</p>
<h2 id="dayanak">5. Hukuki dayanaklar</h2><p>Uygulanabilir mevzuata göre veri işleme; kullanıcıyla kurulan hizmet ilişkisinin kurulması/ifası, açık rıza gereken durumlarda rıza, sistem ve hizmet güvenliğinin sağlanmasına yönelik meşru menfaat, hukuki yükümlülüklerin yerine getirilmesi ve bir hakkın tesisi/kullanılması/korunması gibi hukuki sebeplere dayanabilir. Türkiye'deki kullanıcılar bakımından 6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamındaki haklar saklıdır.</p>
<h2 id="saglayicilar">6. Hizmet sağlayıcılar ve veri paylaşımı</h2><p>Hizmetin çalışması için sınırlı ölçüde üçüncü taraf altyapılar kullanılır. Kimlik doğrulama, veritabanı, depolama ve sunucu işlevlerinde <strong>Supabase</strong>; Android dağıtımı, uygulama içi satın alma, abonelik yönetimi ve satın alma doğrulamasında <strong>Google Play / Google API hizmetleri</strong> kullanılabilir. Destek formu e-posta uygulamasını açtığında kullanıcının seçtiği e-posta sağlayıcısı mesajı işler. Veriler yalnızca ilgili hizmeti sağlamak için gerekli ölçüde paylaşılır; kullanıcı verileri veri brokerlarına satılmaz.</p>
<h2 id="aktarim">7. Uluslararası veri aktarımı</h2><p>Supabase projesinin seçili barındırma bölgesi Asya Pasifik (Singapur) olduğundan hesap ve uygulama verileri teknik hizmetin sunulması kapsamında Türkiye dışında işlenebilir veya barındırılabilir. Google ve diğer hizmet sağlayıcılar da kendi küresel altyapıları kapsamında veri işleyebilir. Uluslararası aktarımlar uygulanabilir veri koruma mevzuatı, sözleşmesel/güvenlik mekanizmaları ve ilgili hizmet sağlayıcıların veri koruma şartları dikkate alınarak yürütülür.</p>
<h2 id="saglik">8. Sağlık, tıbbi içerik ve hassas kullanıcı verileri</h2><p>FTR Akademi bir hasta kayıt sistemi, tıbbi cihaz veya uzaktan tanı/tedavi hizmeti değildir. Uygulama fizyoterapi ve rehabilitasyon alanında eğitim içeriği sunar. Kişisel not alanlarına hasta adı, T.C. kimlik numarası, tıbbi dosya numarası, tanı, görüntüleme sonucu veya kimliği belirlenebilir başka hasta verileri girilmemelidir. Kullanıcı serbest metin alanına kendi isteğiyle hassas bilgi girerse bu bilgi kullanıcı tarafından oluşturulan içerik kapsamında işlenebilir. Eğitim içerikleri profesyonel tıbbi değerlendirme, tanı veya tedavinin yerine geçmez.</p>
<h2 id="guvenlik">9. Güvenlik önlemleri</h2><p>Kişisel veriler aktarım sırasında HTTPS/TLS ile korunur. Kimlik doğrulama Supabase Auth üzerinden yürütülür; şifrelerin uygulama içinde düz metin olarak saklanmaması esastır. Sunucu tarafında kullanıcıya bağlı erişim kontrolleri ve RLS politikaları; Premium işlemlerinde sunucu/mağaza doğrulaması kullanılabilir. Supabase service-role veya benzeri gizli sunucu anahtarları mobil istemciye gömülmez. Buna rağmen hiçbir internet sistemi yüzde yüz güvenlik garantisi veremez.</p>
<h2 id="yerel">10. Yerel cihaz verileri</h2><p>Bazı sürümlerde favoriler, notlar, tamamlanma durumu, okuma konumu ve uygulama tercihleri yalnızca cihazın yerel uygulama alanında tutulabilir. Hesap senkronizasyonu etkinleştirilen özelliklerde aynı tür veriler kullanıcı hesabıyla ilişkilendirilerek sunucuya aktarılabilir. Kullanıcı yerel uygulama verilerini cihaz ayarlarından temizlediğinde yerel kayıtlar kaybolabilir.</p>
<h2 id="saklama">11. Veri saklama ve silme politikası</h2><p>Hesaba bağlı uygulama verileri, hesap aktif olduğu ve ilgili hizmetin sunulması için gerekli olduğu sürece saklanabilir. Hesap kalıcı olarak silindiğinde kullanıcıya bağlı profil, favori, not, ilerleme, quiz ve benzeri uygulama verileri silinir. Güvenlik, dolandırıcılığı önleme, mali kayıt veya uygulanabilir hukuki yükümlülük nedeniyle tutulması zorunlu sınırlı kayıtlar, yalnızca zorunlu süre boyunca kısıtlı biçimde saklanabilir ve reklam profili oluşturmak için kullanılmaz.</p>
<h2 id="silme">12. Hesap ve ilişkili verilerin silinmesi</h2><p>Uygulama hesap oluşturmayı desteklediği için kullanıcıya hesap silme yolu da sunulur. Kullanıcı uygulamadaki <strong>Hesabım → Hesabımı Sil</strong> yolunu kullanabilir veya aşağıdaki herkese açık web sayfasından hesap silme sürecini başlatabilir. Hesap silme geçici dondurma değildir; hesaba bağlı veriler silinir. Google Play aboneliğinin otomatik yenilenmesi Play Store üzerinden ayrıca yönetilir ve uygulama hesabını silmek mağaza aboneliğini kendiliğinden iptal etmeyebilir.</p><p><a href="${DELETE_URL}">FTR Akademi hesap silme sayfasını aç</a></p>
<h2 id="haklar">13. Kullanıcı hakları ve talepler</h2><p>Uygulanabilir mevzuat kapsamında kullanıcı; kişisel verilerinin işlenip işlenmediğini öğrenme, bilgi talep etme, yanlış/eksik verilerin düzeltilmesini isteme, silme veya yok etme talebinde bulunma, işlemeye itiraz etme ve ilgili diğer haklarını kullanabilir. Talepler <a href="mailto:${SUPPORT}">${SUPPORT}</a> adresine iletilebilir. Talebin güvenli biçimde sonuçlandırılması için hesap sahipliğini doğrulamaya yönelik makul bilgiler istenebilir.</p>
<h2 id="cocuklar">14. Çocukların gizliliği</h2><p>FTR Akademi çocuklara yönelik genel tüketici uygulaması olarak tasarlanmamıştır; temel hedef kitlesi fizyoterapi/sağlık eğitimi alan öğrenciler ve yetişkin kullanıcılardır. Hedef kitle beyanı veya ürün özellikleri değişirse Google Play Aileler Politikası ve uygulanabilir çocuk gizliliği kuralları doğrultusunda gerekli ek tedbirler uygulanır.</p>
<h2 id="reklam">15. Reklam, veri satışı ve analiz</h2><p>Mevcut sürümde üçüncü taraf davranışsal reklam SDK'sı veya kullanıcı profili çıkarmaya yönelik reklam sistemi kullanılmamaktadır. Kişisel veriler satılmaz. İleride reklam, analiz veya benzeri yeni bir SDK eklenirse veri işleme başlamadan önce bu politika ve Google Play Veri Güvenliği formu ilgili veri pratiklerini açıkça yansıtacak şekilde güncellenir.</p>
<h2 id="degisiklik">16. Politika değişiklikleri</h2><p>Bu politika uygulama özellikleri, hizmet sağlayıcılar, Google Play gereklilikleri veya mevzuat değiştikçe güncellenebilir. Güncel sürüm her zaman bu herkese açık sayfada yayımlanır. Önemli değişiklikler gerektiğinde uygulama içi bildirim veya uygun başka kanallarla duyurulur.</p>
`);

const terms = page("Kullanım Koşulları ve Tıbbi Bilgilendirme", `
<div class="card"><strong>Önemli:</strong> FTR Akademi eğitim amaçlıdır ve tıbbi cihaz değildir; herhangi bir tıbbi durumu teşhis, tedavi, iyileştirme veya önleme amacı taşımaz. Tıbbi öneri, tanı veya tedavi için yetkin bir sağlık profesyoneline danışılmalıdır.</div>
<h2>1. Eğitim amacı</h2><p>Uygulamadaki dersler, quizler, görseller ve egzersiz açıklamaları fizyoterapi eğitimini desteklemek içindir. Klinik karar verirken yalnızca uygulamaya dayanılmamalı; güncel kılavuzlar, kurum protokolleri, cihaz üretici talimatları ve yetkin sağlık profesyoneli değerlendirmesi esas alınmalıdır.</p>
<h2>2. Acil durumlar</h2><p>Acil veya hızla kötüleşen bir sağlık durumunda uygulama kullanılmamalı; bulunduğunuz yerdeki acil sağlık hizmetlerine başvurulmalıdır.</p>
<h2>3. Hesap ve güvenlik</h2><p>Kullanıcı hesabının ve giriş bilgilerinin güvenliği kullanıcı sorumluluğundadır. Hizmetin kötüye kullanılması, yetkisiz erişim denemeleri veya teknik güvenlik mekanizmalarının aşılması yasaktır.</p>
<h2>4. Premium ve mağaza işlemleri</h2><p>Premium erişim yalnızca desteklenen Google Play işlemi doğrulandıktan sonra etkinleştirilir. Fiyat, yenileme dönemi, vergi ve iptal koşulları satın alma ekranında Google Play tarafından gösterilir. Aboneliğin iptali mağaza hesabından yönetilir.</p>
<h2>5. Fikri haklar</h2><p>Uygulamanın özgün yazılımı, düzeni ve özgün içerikleri ilgili hak sahiplerine aittir. Üçüncü taraf kaynaklar ve lisanslı materyaller kendi kullanım koşullarına tabidir.</p>
<h2>6. Değişiklikler</h2><p>Koşullar hizmetin gelişimine göre güncellenebilir. Güncel metin bu sayfada yayımlanır.</p>
`);

Deno.serve((req: Request) => {
  if (req.method !== "GET" && req.method !== "HEAD") {
    return new Response("Method not allowed", { status: 405, headers: { allow: "GET, HEAD" } });
  }
  const url = new URL(req.url);
  const doc = url.searchParams.get("doc") ?? "privacy";
  const html = doc === "terms" ? terms : privacy;
  return new Response(req.method === "HEAD" ? null : html, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "public, max-age=900",
      "x-content-type-options": "nosniff",
      "content-security-policy": "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'",
      "referrer-policy": "no-referrer",
      "x-frame-options": "DENY",
    },
  });
});